---
- name: Check for Windows updates
  win_updates:
    category_names: '*'
    state: searched
  register: windows_updates

- name: Install Windows updates if available
  win_updates:
    category_names: '*'
    state: installed
  when: windows_updates.updates | length > 0
  register: update_result

- name: Reboot if updates require
  win_reboot:
    reboot_timeout_sec: 300
    async: 0
    poll: 0
  when: update_result.reboot_required | default(false)

- name: Wait for Windows to come back online
  win_ping:
  retries: 300
  delay: 10
  become: false

- name: Check for Windows updates after reboot
  win_updates:
    category_names: '*'
    state: installed
  register: post_reboot_updates

- name: Display update status after reboot
  debug:
    msg: "Updates were installed successfully"
  when: post_reboot_updates.updates | length > 0

- name: Get installed updates
  win_updates:
    state: installed
  register: installed_updates

- name: Display installed updates
  debug:
    var: installed_updates.updates